# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Documentation"
#  url = "docs/"
#  weight = 10

[[main]]
  name = "â¤ï¸ Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 20

[[main]]
  name = "ğŸ“š Notes"
  url = "docs/"
  identifier = "notes"
  weight = 30

[[main]]
  name = "ğŸŒ± Java"
  url = "docs/java/"
  parent = "notes"
  weight = 1




[[main_right]]
  name = "<i class='ai ai-coursera' style='font-size:1.5rem;line-height:1.25'></i>"
  url = "/"
  weight = 10